 ##### 40 Numpy practice Question with answers

In [1]:
import numpy as np

In [2]:
#1. Create a 1D array with values from 0 to 20 using np.arange.
arr1=np.arange(0,21)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
#2. Create an array of 50 zeros and change the 10th value to 5.
arr2=np.zeros(50)
arr2[9]=5
arr2


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#3. Create an array of 100 ones and reshape it to 25×4.
arr3=np.ones(100).reshape(25,4)
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
#4. Create an array of 10 evenly spaced values between 1 and 5 using np.linspace.
arr4=np.linspace(1,5,10)
arr4

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [6]:
#5. Create a 3×3 identity matrix using NumPy.
arr5=np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
#6. Create a 4×4 array filled with the value 7.
# np.full(shape,value): It will fill the array with the given value
arr6=np.full((4,4),7)
arr6


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [8]:
#7. Create a random integer array of size 5×5 with values between 10 and 50.
arr7=np.random.randint(10,50,25).reshape(5,5)     # or we can write np.random.randint(10,50,size=(5,5))
arr7

array([[10, 12, 16, 24, 21],
       [39, 43, 39, 44, 43],
       [21, 15, 47, 25, 27],
       [26, 44, 38, 49, 12],
       [42, 36, 45, 49, 42]], dtype=int32)

In [9]:
#8. Create a 1D array of 20 random normal values using np.random.randn().
arr8=np.random.randn(20)
arr8

array([-0.91360052, -0.25810983, -0.38711696, -1.16800997, -0.16541117,
        0.08208747,  0.27024213,  0.8076956 ,  0.58117893, -1.14874174,
        0.52040146, -0.3831517 ,  1.66741689,  0.26722895,  2.75163967,
       -0.57333618, -0.85513333,  0.26331384,  1.10435439, -0.41101699])

In [10]:
#9. Given an array arr, print its dimensions, shape, size, and datatype
arr9=np.array([10,20,30,40,50])
print(arr9.ndim)
print(arr9.shape)
print(arr9.size)
print(type(arr9))

1
(5,)
5
<class 'numpy.ndarray'>


In [11]:
#10. Convert a 1D array of length 9 into a 3×3 matrix.
arr10=np.arange(1,10).reshape(3,3)
arr10

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#11. Convert a 3×4 matrix into a 1×12 array using reshape.
arr11=np.arange(1,13).reshape(3,4)
print(arr11)
arr11.reshape(1,12)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [13]:
#12. Create a 3D array of shape (2,3,4) and print its shape.
arr=np.arange(1,25).reshape(2,3,4)
arr.shape

(2, 3, 4)

In [14]:
#13. How do you check if an array is C-contiguous or F-contiguous?
arr13=np.arange(1,10)
b=arr13.reshape(3,3)
b.flags
c=np.asfortranarray(b)
c.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [15]:
#14. From array [5,10,15,20,25], extract the third element
arr14=np.array([5,10,15,20,25])
arr14[2]

np.int64(15)

In [17]:
#15. From matrix [[1,2,3],[4,5,6],[7,8,9]], access element 6.
arr15=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr15)
arr15[[1],[2]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([6])