 ##### 40 Numpy practice Question with answers

In [1]:
import numpy as np

In [2]:
#1. Create a 1D array with values from 0 to 20 using np.arange.
arr1=np.arange(0,21)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
#2. Create an array of 50 zeros and change the 10th value to 5.
arr2=np.zeros(50)
arr2[9]=5
arr2


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#3. Create an array of 100 ones and reshape it to 25×4.
arr3=np.ones(100).reshape(25,4)
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
#4. Create an array of 10 evenly spaced values between 1 and 5 using np.linspace.
arr4=np.linspace(1,5,10)
arr4

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [6]:
#5. Create a 3×3 identity matrix using NumPy.
arr5=np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
#6. Create a 4×4 array filled with the value 7.
# np.full(shape,value): It will fill the array with the given value
arr6=np.full((4,4),7)
arr6


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [8]:
#7. Create a random integer array of size 5×5 with values between 10 and 50.
arr7=np.random.randint(10,50,25).reshape(5,5)     # or we can write np.random.randint(10,50,size=(5,5))
arr7

array([[14, 39, 17, 28, 43],
       [36, 36, 29, 42, 46],
       [12, 24, 16, 40, 36],
       [24, 44, 36, 39, 26],
       [21, 17, 31, 10, 18]], dtype=int32)

In [9]:
#8. Create a 1D array of 20 random normal values using np.random.randn().
arr8=np.random.randn(20)
arr8

array([ 2.13550053, -0.41113384, -0.11598538, -0.41811824, -2.1181235 ,
       -0.23976818,  1.24373037, -1.07334579, -1.51883646, -1.89471323,
        0.07837861, -0.42774237,  0.25381229,  1.55299138, -0.34599448,
       -0.14075462, -0.03615661, -1.20099412,  0.14849168,  0.62305494])

In [10]:
#9. Given an array arr, print its dimensions, shape, size, and datatype
arr9=np.array([10,20,30,40,50])
print(arr9.ndim)
print(arr9.shape)
print(arr9.size)
print(type(arr9))

1
(5,)
5
<class 'numpy.ndarray'>


In [11]:
#10. Convert a 1D array of length 9 into a 3×3 matrix.
arr10=np.arange(1,10).reshape(3,3)
arr10

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#11. Convert a 3×4 matrix into a 1×12 array using reshape.
arr11=np.arange(1,13).reshape(3,4)
print(arr11)
arr11.reshape(1,12)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [13]:
#12. Create a 3D array of shape (2,3,4) and print its shape.
arr=np.arange(1,25).reshape(2,3,4)
arr.shape

(2, 3, 4)

In [14]:
#13. How do you check if an array is C-contiguous or F-contiguous?
arr13=np.arange(1,10)
b=arr13.reshape(3,3)
b.flags
c=np.asfortranarray(b)
c.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [15]:
#14. From array [5,10,15,20,25], extract the third element
arr14=np.array([5,10,15,20,25])
arr14[2]

np.int64(15)

In [16]:
#15. From matrix [[1,2,3],[4,5,6],[7,8,9]], access element 6.
arr15=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr15)
arr15[[1],[2]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([6])

In [17]:
#16. Given a 5×5 matrix, extract the center element.
arr16=np.arange(1,26).reshape(5,5)
arr16[[2],[2]]

array([13])

In [18]:
#17. Extract the diagonal elements of a 4×4 matrix.
arr17=np.arange(1,17).reshape(4,4)
np.diagonal(arr17)
arr17[[0,1,2,3],[0,1,2,3]]

array([ 1,  6, 11, 16])

In [19]:
#18. Extract the last element of a 1D array using negative index.
arr18=np.arange(1,6)
arr18[-1]

np.int64(5)

In [20]:
#19. From array [1..20], extract elements from index 5 to 12.
arr19=np.arange(1,21)
print(arr19[5:13])
print(arr19)

[ 6  7  8  9 10 11 12 13]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [21]:
#20. Extract every 2nd element from array [10,20,30,...100].
arr20=np.arange(10,101,10)
arr20[::2]

array([10, 30, 50, 70, 90])

In [22]:
#21. Slice first 2 rows and first 3 columns of a 4×4 matrix.
arr21=np.arange(1,17).reshape(4,4)
arr21[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [23]:
#22. Reverse a NumPy array using slicing.
arr22=np.array([1,2,3,4,5])
arr22[::-1]

array([5, 4, 3, 2, 1])

In [24]:
#23. Slice last 3 elements of an array.
arr23=np.array([1,2,3,4,5])
print(arr23[2:])

[3 4 5]


In [25]:
#24. Given array [10,20,30,40,50], use fancy indexing to extract [50,30,10]
arr24=np.array([10,20,30,40,50])
arr24[[5,2,0]]                          # will show error
arr24[[4,2,0]]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [ ]:
#25. Given a 2D matrix, extract rows 0 and 2.
arr25=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr25[[0,2]])

[[1 2 3]
 [7 8 9]]


In [ ]:
#26. Select columns 1 and 3 from a 4×4 matrix using fancy indexing.
arr26=np.arange(1,17).reshape(4,4)
print(arr26)
arr26[:,[1,3]]                           #fancy indexing

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [ ]:
#27. Rearrange array [1,2,3,4] in the order [4,1,3,2] using an index list.
arr27=np.array([1,2,3,4])
arr27[[3,0,2,1]]


array([4, 1, 3, 2])

In [ ]:
#28. Extract elements at positions (0,0), (1,1), (2,2) using fancy indexing.
arr28=np.arange(1,10).reshape(3,3)
print(arr28)
arr28[[0,1,2],[0,1,2]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 5, 9])

In [ ]:
#29. Use np.where to replace all negative numbers in an array with 0.
arr29=np.array([1,-2,3,-4,5])
print(arr29)
np.where(arr29<0,0,arr29)

[ 1 -2  3 -4  5]


array([1, 0, 3, 0, 5])

In [ ]:
#30. Use np.where to extract all numbers greater than 50 from a random array.
arr30=np.random.randint(1,100,70)
print(arr30)
arr30[np.where(arr30>50)]

[57 19 25 58 94 78 35  1 27 17 46 41 25 69 37 81 91 25 46 25 23  3 81 52
 56 33 31  5 88  4 82 91 15 15 97 18 79 54 30 26 36 39 19 53 32 60 41 19
 36 65 19 66 28 94 94 20  9 29 23 26 65 66 34 74 82  2 18  4 78 27]


array([57, 58, 94, 78, 69, 81, 91, 81, 52, 56, 88, 82, 91, 97, 79, 54, 53,
       60, 65, 66, 94, 94, 65, 66, 74, 82, 78], dtype=int32)