 ##### 40 Numpy practice Question with answers

In [1]:
import numpy as np

In [2]:
#1. Create a 1D array with values from 0 to 20 using np.arange.

arr1=np.arange(0,21)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
#2. Create an array of 50 zeros and change the 10th value to 5.

arr2=np.zeros(50)
arr2[9]=5
arr2


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#3. Create an array of 100 ones and reshape it to 25×4.

arr3=np.ones(100).reshape(25,4)
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
#4. Create an array of 10 evenly spaced values between 1 and 5 using np.linspace.

arr4=np.linspace(1,5,10)
arr4

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [6]:
#5. Create a 3×3 identity matrix using NumPy.

arr5=np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
#6. Create a 4×4 array filled with the value 7.
# np.full(shape,value): It will fill the array with the given value

arr6=np.full((4,4),7)
arr6


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [8]:
#7. Create a random integer array of size 5×5 with values between 10 and 50.

arr7=np.random.randint(10,50,25).reshape(5,5)     # or we can write np.random.randint(10,50,size=(5,5))
arr7

array([[40, 29, 20, 25, 40],
       [44, 45, 17, 41, 26],
       [48, 15, 20, 40, 37],
       [27, 10, 22, 24, 14],
       [17, 32, 31, 42, 48]], dtype=int32)

In [ ]:
#8. Create a 1D array of 20 random normal values using np.random.randn().

arr8=np.random.randn(20)
arr8

array([-1.35923371,  1.56858136, -0.20595877, -0.30637665,  0.42011942,
        0.13389471,  0.04597635,  0.6835832 , -0.60496981, -1.16484158,
        0.28540741,  0.47853197, -0.51014523, -2.21209536,  2.66303243,
       -0.81627583,  0.60711807, -0.75530102, -0.94599372,  2.21396018])

In [10]:
#9. Given an array arr, print its dimensions, shape, size, and datatype

arr9=np.array([10,20,30,40,50])
print(arr9.ndim)
print(arr9.shape)
print(arr9.size)
print(type(arr9))

1
(5,)
5
<class 'numpy.ndarray'>


In [11]:
#10. Convert a 1D array of length 9 into a 3×3 matrix.

arr10=np.arange(1,10).reshape(3,3)
arr10

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])