# Numpy

In [ ]:
"""

pip install numpy   ------> to install numpy in vs code

import numpy as np  (importing numpy and giving "np" as alias name)

Numpy is an numerical python which deals with array. It consist of homogeneous values and store in sequential format

Array is faster compare to list. It is used to create multi dimentional array

"""

In [2]:
import numpy as np

### 08-11-25
#### Creation of array

In [2]:
a=np.array([1,2,3,'pc'])
a

array(['1', '2', '3', 'pc'], dtype='<U21')

In [3]:
a=[1,2,3,4]
arr=np.array(a)
arr

array([1, 2, 3, 4])

#### types of array

In [ ]:
a=12+4j                         # or we can take 1 or 2 or 3 etc
arr0=np.array(a)
arr0
print(arr0.ndim)                # 0-D Array


b=[1,2,3,4]
arr1=np.array(b)
arr1
print(arr1.ndim )               # 1-D Array


c=[[1,2,3,4,5,6,7,8]]           # or we can take   [[1,2,3,4],[5,6,7,8]]
arr2=np.array(c)
arr2
print(arr2.ndim )               # 2-D Array


d=[[[1,2,3,4]]]
arr3=np.array(d)
arr3
print(arr3.ndim )               # 3-D Array


0
1
2
3


#### to check type of array

In [ ]:
a=[1,2,3,4,5]
arr=np.array(a)
print(type(arr))                         # numpy.ndarray



a=[1,2,3,4,5]
arr=np.array(a)
print(type(arr[0]))                     # numpy.int64


a=[1,2,3,4,5.5]
arr=np.array(a)
print(type(arr[0]))                    # numpy.float64


a=[1,2,3,4,5.5,True]
arr=np.array(a)
print(type(arr[0]) )                   # numpy.float64


<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


### 09-11-25

In [6]:
"""
reshape:- It is an inbuild function used to reshape the array or to change the shape. It will change the dimention
product of row and column must be equal to no of element

"""
a=[1,2,3,4,5,6]
arr1=np.array(a)
print(arr1.reshape(1,6))
print(arr1.reshape(2,3))
print(arr1.reshape(3,2))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [3]:
b=[[1,2,3],
   [4,5,6],
   [7,8,9]]
arr2=np.array(b)
print(arr2.reshape(3,3))
print(arr2.reshape(3,3,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [4]:
# flattening of array ----> Here we can change any no of dimention to 1 dimention array

c=[[[[1,2,3],
   [4,5,6],
   [7,8,9],
   [10,11,12],
   [13,14,15]]]]
arr3=np.array(c)
print(arr3.reshape(-1))                # we take 4-D array and it converted to 1-D array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [5]:
# ndim used to find the dimention of the array

d=[[[[[[[[1,2,3,4]]]]]]]]          # no of[] = no of dimension

arr4=np.array(d)
print(arr4.ndim)
arr2=arr4.reshape(2,2)
print(arr4.reshape(2,2))
abc=arr2.ndim                           
print(abc)

8
[[1 2]
 [3 4]]
2


In [6]:
"""
arrange:- It is a inbuilt function  to create sequence of values

syntax :- np.arrange(S.V,E.V,UP)

"""
print(np.arange(1,21,1))            # in python we use range and in numpy we use arange



e=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
arr5=np.array(e)
print(arr5.reshape(4,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
