# Numpy

In [2]:
"""

pip install numpy   ------> to install numpy in vs code

import numpy as np  (importing numpy and giving "np" as alias name)

Numpy is an numerical python which deals with array. It consist of homogeneous values and store in sequential format

Array is faster compare to list. It is used to create multi dimentional array

"""

'\n\npip install numpy   ------> to install numpy in vs code\n\nimport numpy as np  (importing numpy and giving "np" as alias name)\n\nNumpy is an numerical python which deals with array. It consist of homogeneous values and store in sequential format\n\nArray is faster compare to list. It is used to create multi dimentional array\n\n'

In [3]:
import numpy as np

### 08-11-25
#### Creation of array

In [4]:
a=np.array([1,2,3,'pc'])
a

array(['1', '2', '3', 'pc'], dtype='<U21')

In [5]:
a=[1,2,3,4]
arr=np.array(a)
arr

array([1, 2, 3, 4])

#### types of array

In [6]:
a=12+4j                         # or we can take 1 or 2 or 3 etc
arr0=np.array(a)
arr0
print(arr0.ndim)                # 0-D Array


b=[1,2,3,4]
arr1=np.array(b)
arr1
print(arr1.ndim )               # 1-D Array


c=[[1,2,3,4,5,6,7,8]]           # or we can take   [[1,2,3,4],[5,6,7,8]]
arr2=np.array(c)
arr2
print(arr2.ndim )               # 2-D Array


d=[[[1,2,3,4]]]
arr3=np.array(d)
arr3
print(arr3.ndim )               # 3-D Array


0
1
2
3


#### to check type of array

In [7]:
a=[1,2,3,4,5]
arr=np.array(a)
print(type(arr))                         # numpy.ndarray



a=[1,2,3,4,5]
arr=np.array(a)
print(type(arr[0]))                     # numpy.int64


a=[1,2,3,4,5.5]
arr=np.array(a)
print(type(arr[0]))                    # numpy.float64


a=[1,2,3,4,5.5,True]
arr=np.array(a)
print(type(arr[0]) )                   # numpy.float64


<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


### 09-11-25

In [8]:
"""
reshape:- It is an inbuild function used to reshape the array or to change the shape. It will change the dimention
product of row and column must be equal to no of element

"""
a=[1,2,3,4,5,6]
arr1=np.array(a)
print(arr1.reshape(1,6))
print(arr1.reshape(2,3))
print(arr1.reshape(3,2))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [9]:
b=[[1,2,3],
   [4,5,6],
   [7,8,9]]
arr2=np.array(b)
print(arr2.reshape(3,3))
print(arr2.reshape(3,3,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [10]:
# flattening of array ----> Here we can change any no of dimention to 1 dimention array

c=[[[[1,2,3],
   [4,5,6],
   [7,8,9],
   [10,11,12],
   [13,14,15]]]]
arr3=np.array(c)
print(arr3.reshape(-1))                # we take 4-D array and it converted to 1-D array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [11]:
# ndim used to find the dimention of the array

d=[[[[[[[[1,2,3,4]]]]]]]]          # no of[] = no of dimension

arr4=np.array(d)
print(arr4.ndim)
arr2=arr4.reshape(2,2)
print(arr4.reshape(2,2))
abc=arr2.ndim                           
print(abc)

8
[[1 2]
 [3 4]]
2


In [12]:
"""
arrange:- It is a inbuilt function  to create sequence of values

syntax :- np.arrange(S.V,E.V,UP)

"""
print(np.arange(1,21,1))            # in python we use range and in numpy we use arange



e=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
arr5=np.array(e)
print(arr5.reshape(4,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [13]:
# WAF(Write A Function) to find prime numbers between 1 to 100

l1=[]
def find_primes():
    for num in range(2, 101):                       # numbers from 2 to 100
        for i in range(2, int(num ** 0.5) + 1):     # check divisibility up to sqrt(num)
            if num % i == 0:
                break
        else:
            l1.append(num)    


find_primes()                                       # call the function
print(l1)
print(type(l1))

length=len(l1)
print(length)

arr6=np.array(l1)
print(arr6)

print(type(arr6))

arr6.reshape(5,5)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
<class 'list'>
25
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]
<class 'numpy.ndarray'>


array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29],
       [31, 37, 41, 43, 47],
       [53, 59, 61, 67, 71],
       [73, 79, 83, 89, 97]])

#### Random Module

In [14]:
"""
Random Module
syntax:- np.random.randint(S.V,E.V,n)-------> n is number of values required  n is optional by default it will give only one value

"""
a1=np.random.randint(1,10)                    # It will give 1 random value
print(a1)

a2=np.random.randint(1,10,5)                  # It will give 5 random value
print(a2)

a3=np.random.randint(1,100,20)                # It will give 20 random value
print(a3)


7
[1 9 6 4 9]
[54 95 77 67 44 98 15 39 41 72 33 53 36 41 62 82 23 19 23 86]


In [15]:
# np.random.rand(n) --------> n is numer of values . It is optional  by default it will give one value

a4=np.random.rand(3)
print(a4)

[0.38990679 0.2112674  0.07891095]


In [16]:
# np.random.randn(n)-------------->n is number of values
# It will give random values which includes float number

a5=np.random.randn(5)
print(a5)

[ 0.04550121 -0.26304454 -0.82083962  0.44354503 -0.37836973]


### 10-11-25

In [17]:
a=[1,2,3,4,5,6]
arr1=np.array(a)
print(arr1.reshape(1,6)) 
print(arr1.reshape(2,3))
print(arr1.reshape(3,2))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [18]:
# Q.1 (Create a 2-d array of shape (3,3) filled with integer between  to 10)

a=np.random.randint(1,11,9)
b=np.array(a)
c=b.reshape(3,3)
print(c)


# other

arr=np.random.randint(1,11,(3,3))
print(arr)

[[ 6  7  9]
 [ 1  5  1]
 [ 7 10  1]]
[[5 1 9]
 [6 7 6]
 [9 6 4]]


In [19]:
# Q.2 find shape,dimention & data type of an array

a=[[1, 2, 3], [4, 5, 6]]
arr = np.array(a)

print("Shape:", arr.shape)

print("Dimension:", arr.ndim)

print("Data type:", arr.dtype)


Shape: (2, 3)
Dimension: 2
Data type: int64


In [20]:
# Q.3 

arr = np.arange(2, 21, 2)   #np.arange(start, stop, step)

print(arr)


[ 2  4  6  8 10 12 14 16 18 20]


In [21]:
# q.4


# create 1D array with 9 elements
arr = np.arange(1, 10)

print("1D Array:")
print(arr)

# reshape into 3x3
reshaped_arr = arr.reshape(3, 3)

print("\nReshaped 3x3 Array:")
print(reshaped_arr)


1D Array:
[1 2 3 4 5 6 7 8 9]

Reshaped 3x3 Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
# Q.5 Flattening of an array 
# it means convert any dimention array to 1d array


# 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flatten the array
flat_arr = arr.flatten()

print("Original Array:\n", arr)
print("\nFlattened Array:\n", flat_arr)


Original Array:
 [[1 2 3]
 [4 5 6]]

Flattened Array:
 [1 2 3 4 5 6]


In [23]:
# np.random.rand(n)  inbuild function to generate random float number between -infinity to =infinity

np.random.rand(10) 

array([0.07278997, 0.76905608, 0.58696556, 0.27280416, 0.55222917,
       0.19907674, 0.33122195, 0.28581596, 0.68870983, 0.14639525])

In [24]:
# np.linspace(S.V,E.V,n)  n---> it is number of partition 
# it is used to divide the given range from range from s.v to e.v  in to n equal parts


np.linspace(1,20,4)


array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [25]:
# np.zeros() ---->Initialize an array or matrix with all zero values (often used before filling it with other data).

arr = np.zeros((3, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
# np.ones() ------> Creates an array filled with all ones.


arr = np.ones((2, 4))
print((arr))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
# np.identity() ------> Creates a square identity matrix — a matrix with 1s on the diagonal and 0s elsewhere.

arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Copy operation

In [28]:
"""
Shallow copy:- It is sopy operation when the value space will get copied to dest_variable
Syntax:- dest_var=src_val.copy()

"""
b=np.array([1,2,3,4,5])
c=b.copy()
b[1]=10
b

array([ 1, 10,  3,  4,  5])

In [29]:
"""
View()

"""

d=np.array([1,2,3,4,5])
e=d.view()
e[2]=30
d

array([ 1,  2, 30,  4,  5])

In [30]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

In [31]:
"""
Difference between normal copy() & view():-
In normal copy src_var & dest_var will have same address
In view() src_var & dest_var will have different address

"""

'\nDifference between normal copy() & view():-\nIn normal copy src_var & dest_var will have same address\nIn view() src_var & dest_var will have different address\n\n'

### 11-11-25

In [32]:
# INDEXING
# var[S.V,E.V,UPDATION]
# array[row_selection, column_selection]


arr=np.array([1,2,3,4,5])
arr[2]
arr[-1]

arr[2::]                #array([3, 4, 5])
arr[::2]                #array([1, 3, 5])

array([1, 3, 5])

In [33]:
# array[row_selection, column_selection]


arr2=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2[1][2]
arr2[2][2]
arr2[1::,1::]

array([[5, 6],
       [8, 9]])

In [34]:
arr3=np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20],
               [21,22,23,24,25]])
arr3[ : :  ,3:5:1]
arr3[3:5:1 ,2:5:1]
arr3[2:5:1 ,1:4:2]   # here last index is 4 so if we take 5 then ok or we can just leave and for updation if 1 then leave space arr3[2:0:1 ,1:4:2]  
arr3[3:5:1 ,0:5:2]   # here last index is 4 so if we take 5 then ok or we can just leave and for updation if 1 then leave space arr3[3:: ,0::2] 
arr3[0:3:1 ,0:3:1]
arr3[::2,::2]
arr3[::4,::2]



array([[ 1,  3,  5],
       [21, 23, 25]])

### 13-11-25

### OPERATORS:-

##### ARITHMETIC OPERATORS

In [35]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1+arr2 #array([ 7,  9, 11, 13, 15])
np.add(arr1,arr2) #array([ 7,  9, 11, 13, 15])

array([ 7,  9, 11, 13, 15])

In [36]:
# np.add(op1,op2): it will add two arrays w.r.to index


arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1-arr2)                                      #array([-5, -5, -5, -5, -5])
print(arr2-arr1)                                      #array([5, 5, 5, 5, 5])
print(arr1*arr2)                                      #array([ 6, 14, 24, 36, 50])
print(arr1/arr2)                                      #array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])
print(arr1//arr2)                                     #array([0, 0, 0, 0, 0])
print(arr1%arr2)                                      #array([1, 2, 3, 4, 5])
print(arr1**arr2)                                     #array([      1,     128,    6561,  262144, 9765625])
print(np.power(arr1,arr2))                            #array([      1,     128,    6561,  262144, 9765625])


[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0 0 0 0 0]
[1 2 3 4 5]
[      1     128    6561  262144 9765625]
[      1     128    6561  262144 9765625]


##### RELATIONAL OPERATORS

In [37]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,3,5])
print(arr1>arr2)                                  #array([False, False, False,  True, False])
print(arr1>=arr2)                                 #array([ True,  True,  True,  True,  True])
print(arr1<arr2)                                  #array([False, False, False, False, False])
print(arr1<=arr2)                                 #array([ True,  True,  True, False,  True])
print(arr1!=arr2)                                 #array([False, False, False,  True, False])
print(arr1==arr2)                                 #array([ True,  True,  True, False,  True])

[False False False  True False]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True False  True]
[False False False  True False]
[ True  True  True False  True]


##### BITWISE OPERATORS

In [38]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print("and",arr1&arr2)                    #and [0 2 0 0 0]
print("or",arr1|arr2)                     #or [ 7  7 11 13 15]
print("not",~arr1)                        #not [-2 -3 -4 -5 -6]
print("xor",arr1^arr2)                    #xor [ 7  5 11 13 15]

and [0 2 0 0 0]
or [ 7  7 11 13 15]
not [-2 -3 -4 -5 -6]
xor [ 7  5 11 13 15]


##### LOGICAL OPERATORS

In [39]:
print(np.logical_and(arr1,arr2))           #array([ True,  True,  True,  True,  True])
print(np.logical_or(arr1,arr2))            #array([ True,  True,  True,  True,  True])
print(np.logical_not(arr1))                #array([False, False, False, False, False])

[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


In [40]:
# np.sum(op):- It will give sum of all elements in the array
print(np.sum(arr1))                          #np.int64(15) 


# np.mean(op):- It will give the average of all the elements present in a array
print(np.mean(arr1))                         #np.float64(3.0)


# np.max(op):- It will give maximum value among the array
print(np.max(arr1))                          #np.int64(5)


# np.min:- It will give minimum value among the array
print(np.min(arr1))                          #np.int64(1)


# np.count_nonzero(op):- Count of elements
print(np.count_nonzero(arr1))                #5

15
3.0
5
1
5
