# Numpy

In [2]:
"""

pip install numpy   ------> to install numpy in vs code

import numpy as np  (importing numpy and giving "np" as alias name)

Numpy is an numerical python which deals with array. It consist of homogeneous values and store in sequential format

Array is faster compare to list. It is used to create multi dimentional array

"""

'\n\npip install numpy   ------> to install numpy in vs code\n\nimport numpy as np  (importing numpy and giving "np" as alias name)\n\nNumpy is an numerical python which deals with array. It consist of homogeneous values and store in sequential format\n\nArray is faster compare to list. It is used to create multi dimentional array\n\n'

In [3]:
import numpy as np

### 08-11-25
#### Creation of array

In [4]:
a=np.array([1,2,3,'pc'])
a

array(['1', '2', '3', 'pc'], dtype='<U21')

In [5]:
a=[1,2,3,4]
arr=np.array(a)
arr

array([1, 2, 3, 4])

#### types of array

In [6]:
a=12+4j                         # or we can take 1 or 2 or 3 etc
arr0=np.array(a)
arr0
print(arr0.ndim)                # 0-D Array


b=[1,2,3,4]
arr1=np.array(b)
arr1
print(arr1.ndim )               # 1-D Array


c=[[1,2,3,4,5,6,7,8]]           # or we can take   [[1,2,3,4],[5,6,7,8]]
arr2=np.array(c)
arr2
print(arr2.ndim )               # 2-D Array


d=[[[1,2,3,4]]]
arr3=np.array(d)
arr3
print(arr3.ndim )               # 3-D Array


0
1
2
3


#### to check type of array

In [7]:
a=[1,2,3,4,5]
arr=np.array(a)
print(type(arr))                         # numpy.ndarray



a=[1,2,3,4,5]
arr=np.array(a)
print(type(arr[0]))                     # numpy.int64


a=[1,2,3,4,5.5]
arr=np.array(a)
print(type(arr[0]))                    # numpy.float64


a=[1,2,3,4,5.5,True]
arr=np.array(a)
print(type(arr[0]) )                   # numpy.float64


<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


### 09-11-25

In [8]:
"""
reshape:- It is an inbuild function used to reshape the array or to change the shape. It will change the dimention
product of row and column must be equal to no of element

"""
a=[1,2,3,4,5,6]
arr1=np.array(a)
print(arr1.reshape(1,6))
print(arr1.reshape(2,3))
print(arr1.reshape(3,2))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [9]:
b=[[1,2,3],
   [4,5,6],
   [7,8,9]]
arr2=np.array(b)
print(arr2.reshape(3,3))
print(arr2.reshape(3,3,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [10]:
# flattening of array ----> Here we can change any no of dimention to 1 dimention array

c=[[[[1,2,3],
   [4,5,6],
   [7,8,9],
   [10,11,12],
   [13,14,15]]]]
arr3=np.array(c)
print(arr3.reshape(-1))                # we take 4-D array and it converted to 1-D array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [11]:
# ndim used to find the dimention of the array

d=[[[[[[[[1,2,3,4]]]]]]]]          # no of[] = no of dimension

arr4=np.array(d)
print(arr4.ndim)
arr2=arr4.reshape(2,2)
print(arr4.reshape(2,2))
abc=arr2.ndim                           
print(abc)

8
[[1 2]
 [3 4]]
2


In [12]:
"""
arrange:- It is a inbuilt function  to create sequence of values

syntax :- np.arrange(S.V,E.V,UP)

"""
print(np.arange(1,21,1))            # in python we use range and in numpy we use arange



e=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
arr5=np.array(e)
print(arr5.reshape(4,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [13]:
# WAF(Write A Function) to find prime numbers between 1 to 100

l1=[]
def find_primes():
    for num in range(2, 101):                       # numbers from 2 to 100
        for i in range(2, int(num ** 0.5) + 1):     # check divisibility up to sqrt(num)
            if num % i == 0:
                break
        else:
            l1.append(num)    


find_primes()                                       # call the function
print(l1)
print(type(l1))

length=len(l1)
print(length)

arr6=np.array(l1)
print(arr6)

print(type(arr6))

arr6.reshape(5,5)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
<class 'list'>
25
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]
<class 'numpy.ndarray'>


array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29],
       [31, 37, 41, 43, 47],
       [53, 59, 61, 67, 71],
       [73, 79, 83, 89, 97]])

#### Random Module

In [14]:
"""
Random Module
syntax:- np.random.randint(S.V,E.V,n)-------> n is number of values required  n is optional by default it will give only one value

"""
a1=np.random.randint(1,10)                    # It will give 1 random value
print(a1)

a2=np.random.randint(1,10,5)                  # It will give 5 random value
print(a2)

a3=np.random.randint(1,100,20)                # It will give 20 random value
print(a3)


3
[4 1 4 5 6]
[ 1 92 22 75 53 82 93 83 31 55 43 96 11 45 49 72 71  6 25 48]


In [15]:
# np.random.rand(n) --------> n is numer of values . It is optional  by default it will give one value

a4=np.random.rand(3)
print(a4)

[0.60483478 0.50425835 0.11663117]


In [16]:
# np.random.randn(n)-------------->n is number of values
# It will give random values which includes float number

a5=np.random.randn(5)
print(a5)

[-1.01880732 -0.9693715   1.73000336  0.60338289  0.09048587]


### 10-11-25

In [17]:
a=[1,2,3,4,5,6]
arr1=np.array(a)
print(arr1.reshape(1,6)) 
print(arr1.reshape(2,3))
print(arr1.reshape(3,2))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [18]:
# Q.1 (Create a 2-d array of shape (3,3) filled with integer between  to 10)

a=np.random.randint(1,11,9)
b=np.array(a)
c=b.reshape(3,3)
print(c)


# other

arr=np.random.randint(1,11,(3,3))
print(arr)

[[ 5  2  7]
 [ 3  3  1]
 [10  8 10]]
[[ 1  3  6]
 [ 4 10  8]
 [ 7  9  6]]


In [19]:
# Q.2 find shape,dimention & data type of an array

a=[[1, 2, 3], [4, 5, 6]]
arr = np.array(a)

print("Shape:", arr.shape)

print("Dimension:", arr.ndim)

print("Data type:", arr.dtype)


Shape: (2, 3)
Dimension: 2
Data type: int64


In [20]:
# Q.3 

arr = np.arange(2, 21, 2)   #np.arange(start, stop, step)

print(arr)


[ 2  4  6  8 10 12 14 16 18 20]


In [21]:
# q.4


# create 1D array with 9 elements
arr = np.arange(1, 10)

print("1D Array:")
print(arr)

# reshape into 3x3
reshaped_arr = arr.reshape(3, 3)

print("\nReshaped 3x3 Array:")
print(reshaped_arr)


1D Array:
[1 2 3 4 5 6 7 8 9]

Reshaped 3x3 Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
# Q.5 Flattening of an array 
# it means convert any dimention array to 1d array


# 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flatten the array
flat_arr = arr.flatten()

print("Original Array:\n", arr)
print("\nFlattened Array:\n", flat_arr)


Original Array:
 [[1 2 3]
 [4 5 6]]

Flattened Array:
 [1 2 3 4 5 6]


In [23]:
# np.random.rand(n)  inbuild function to generate random float number between -infinity to =infinity

np.random.rand(10) 

array([0.10342474, 0.55424202, 0.55449836, 0.11972706, 0.39219738,
       0.44510008, 0.48760968, 0.35114779, 0.97679965, 0.58579966])