# Numpy

In [1]:
"""

pip install numpy   ------> to install numpy in vs code

import numpy as np  (importing numpy and giving "np" as alias name)

Numpy is an numerical python which deals with array. It consist of homogeneous values and store in sequential format

Array is faster compare to list. It is used to create multi dimentional array

"""

'\n\npip install numpy   ------> to install numpy in vs code\n\nimport numpy as np  (importing numpy and giving "np" as alias name)\n\nNumpy is an numerical python which deals with array. It consist of homogeneous values and store in sequential format\n\nArray is faster compare to list. It is used to create multi dimentional array\n\n'

In [2]:
import numpy as np

### 08-11-25
#### Creation of array

In [3]:
a=np.array([1,2,3,'pc'])
a

array(['1', '2', '3', 'pc'], dtype='<U21')

In [4]:
a=[1,2,3,4]                     # or a=(1,2,3,4) we can take any type
arr=np.array(a)                 # here we converted to array
arr

array([1, 2, 3, 4])

#### types of array

In [5]:
"""
5 types of array 1-D ,2-D, 3-D, 4-D, Multi-Dimention Array
ndim is used to check dimension of a array

"""

a=12+4j                         # or we can take 1 or 2 or 3 etc
arr0=np.array(a)
arr0
print(arr0.ndim)                # 0-Dimension Array(scaler)

b=[1,2,3,4]
arr1=np.array(b)
arr1
print(arr1.ndim )               # 1-Dimension Array(vector)

c=[[1,2,3,4,5,6,7,8]]           # or we can take   [[1,2,3,4],[5,6,7,8]]
arr2=np.array(c)
arr2
print(arr2.ndim )               # 2-Dimension Array(matrics)

d=[[[1,2,3,4]]]
arr3=np.array(d)
arr3
print(arr3.ndim )               # 3-Dimension Array(tensor)

0
1
2
3


#### to check type of array

In [6]:
# type() used to check datatype of a variable

a=[1,2,3,4,5]
arr=np.array(a)
print(type(arr))                        # numpy.ndarray



a=[1,2,3,4,5]
arr=np.array(a)
print(type(arr[0]))                     # numpy.int64


a=[1,2,3,4,5.5]
arr=np.array(a)
print(type(arr[0]))                     # numpy.float64


a=[1,2,3,4,5.5,True]
arr=np.array(a)
print(type(arr[0]) )                    # numpy.float64


<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


### 09-11-25

In [7]:
"""
.shape:-
shape tells you the dimensions (structure) of a NumPy array.

"""

# Shape of a 1D array
arr = np.array([1,2,3,4,5])
print(arr.shape,'\n')                               # (5,) means: 1 row, 5 elements, means 1D array with length 5.

# Shape of a 2D array (Matrix)
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr.shape,'\n')                                # (2, 3) means 2 row 3 col

# Shape of a 3D array
arr = np.array([ [[1,2],[3,4]], 
                 [[5,6],[7,8]] ])
print(arr.shape)                                     #(2, 2, 2)(block,row,col) means 2 blocks each block has 2 rows each row has 2 columns


(5,) 

(2, 3) 

(2, 2, 2)


In [8]:
# Using shape to understand reshape

arr = np.arange(12)
print(arr.shape)                        # (12,)
print(arr.reshape(3,4).shape)           #(3, 4)

(12,)
(3, 4)


In [9]:
"""
shape helps you know if reshape is possible
You cannot reshape it to (3,3) → because 10 ≠ 9.
You can reshape to:
(2,5)
(5,2)
(10,1)
(1,10)

"""

arr = np.arange(10)
print(arr.shape)    # (10,)


(10,)


In [10]:
"""
reshape:- It is an inbuild function used to reshape the array or to change the shape. It will change the dimention.
Product of row and column must be equal to no of element

"""
a=[1,2,3,4,5,6]
arr=np.array(a)
print(arr.reshape(1,6),'\n')
print(arr.reshape(2,3),'\n')
print(arr.reshape(3,2),)

[[1 2 3 4 5 6]] 

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]]


In [11]:
# 1D → 3D reshape

b = np.array([1,2,3,4,5,6,7,8])
arr1 = b.reshape(2,2,2)                #3D shape = (2 blocks × 2 rows × 2 cols)
print(arr1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
c=[[1,2,3],
   [4,5,6],
   [7,8,9]]
arr2=np.array(c)
print(arr2.reshape(3,3),'\n')
print(arr2.reshape(3,3,1),'\n')
print(arr2.reshape(1,3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]] 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [13]:
# flattening of array ----> Here we can change any no of dimention to 1 dimention array

d=[[[[1,2,3],
   [4,5,6],
   [7,8,9],
   [10,11,12],
   [13,14,15]]]]
arr3=np.array(d)
print(arr3.reshape(-1))                # we take 4-D array and it converted to 1-D array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [63]:
e=[[[[[[[[1,2,3,4]]]]]]]]          # no of[] = no of dimension
print(type(e))

arr4=np.array(e)
print(arr4.ndim,'\n')              # 8-D Array (ndim used to find the dimention of the array)

arr5=arr4.reshape(2,2)             # Converted to 2-D Array
print(arr5,'\n')

abc=arr5.ndim                           
print(abc)                         # O/p is 2-D Array

arr4.shape

<class 'list'>
8 

[[1 2]
 [3 4]] 

2


(1, 1, 1, 1, 1, 1, 1, 4)

In [ ]:
"""
arange:- It is a inbuilt function  to create sequence of values

syntax :- np.arrange(S.V,E.V,UP)

"""
print(np.arange(1,21,1))            # in python we use range and in numpy we use arange



e=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
arr5=np.array(e)
print(arr5.reshape(4,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# WAF(Write A Function) to find prime numbers between 1 to 100

l1=[]
def find_primes():
    for num in range(2, 101):                       # numbers from 2 to 100
        for i in range(2, int(num ** 0.5) + 1):     # check divisibility up to sqrt(num)
            if num % i == 0:
                break
        else:
            l1.append(num)

find_primes()                                       # call the function
print(l1,'\n')
print(type(l1),'\n')

length=len(l1)
print(length,'\n')

arr6=np.array(l1)                                   # converted list to numpy array
print(arr6,'\n')

print(type(arr6),'\n')                              # <class 'numpy.ndarray'>                               

arr6.reshape(5,5)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97] 

<class 'list'> 

25 

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97] 

<class 'numpy.ndarray'> 



array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29],
       [31, 37, 41, 43, 47],
       [53, 59, 61, 67, 71],
       [73, 79, 83, 89, 97]])

#### Random Module

In [ ]:
"""
Random Module:- It is used to generate random numbers
syntax:- np.random.randint(S.V,E.V,n)-------> n is number of values required  n is optional by default it will give only one value

randint used to generate random Integers

"""
a1=np.random.randint(1,10)                    # It will give 1 random value
print(a1)

a2=np.random.randint(1,10,5)                  # It will give 5 random value
print(a2)

a3=np.random.randint(1,100,20)                # It will give 20 random value
print(a3)


4
[6 9 8 2 6]
[24 55 55 80 93 98 39 83 26 17 65 47 99 86 37 40 56 54 70 45]


In [ ]:
"""
rand — Random Float Numbers (0 to 1)
np.random.rand(n) --------> n is numer of values . It is optional  by default it will give one value

"""


a4=np.random.rand(3)
print(a4)

[0.17308972 0.89113691 0.15934811]


In [ ]:
"""
np.random.randn(n)-------------->n is number of values
randn :- It will give random float values which includes positive & negative values
"""
a5=np.random.randn(5)
print(a5)

[ 0.57848302 -0.73704968  0.03341672 -0.22951293  0.29724227]


### 10-11-25

In [20]:
a=[1,2,3,4,5,6]
arr1=np.array(a)
print(arr1.reshape(1,6)) 
print(arr1.reshape(2,3))
print(arr1.reshape(3,2))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [21]:
# Q.1 (Create a 2-d array of shape (3,3) filled with integer between  to 10)

a=np.random.randint(1,11,9)
b=np.array(a)
c=b.reshape(3,3)
print(c)


# other

arr=np.random.randint(1,11,(3,3))
print(arr)

[[ 6  1  5]
 [ 1  2 10]
 [ 6  9  2]]
[[9 9 5]
 [6 2 4]
 [8 5 6]]


In [22]:
# Q.2 find shape,dimention & data type of an array

a=[[1, 2, 3], [4, 5, 6]]
arr = np.array(a)

print("Shape:", arr.shape)

print("Dimension:", arr.ndim)

print("Data type:", arr.dtype)


Shape: (2, 3)
Dimension: 2
Data type: int64


In [23]:
# Q.3 

arr = np.arange(2, 21, 2)   #np.arange(start, stop, step)

print(arr)


[ 2  4  6  8 10 12 14 16 18 20]


In [24]:
# q.4


# create 1D array with 9 elements
arr = np.arange(1, 10)

print("1D Array:")
print(arr)

# reshape into 3x3
reshaped_arr = arr.reshape(3, 3)

print("\nReshaped 3x3 Array:")
print(reshaped_arr)


1D Array:
[1 2 3 4 5 6 7 8 9]

Reshaped 3x3 Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
# Q.5 Flattening of an array 
# it means convert any dimention array to 1d array


# 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flatten the array
flat_arr = arr.flatten()

print("Original Array:\n", arr)
print("\nFlattened Array:\n", flat_arr)


Original Array:
 [[1 2 3]
 [4 5 6]]

Flattened Array:
 [1 2 3 4 5 6]


In [26]:
# np.random.rand(n)  inbuild function to generate random float number between -infinity to =infinity

np.random.rand(10) 

array([0.46319459, 0.79869225, 0.08134216, 0.89507735, 0.88911616,
       0.69333734, 0.25398664, 0.93896588, 0.70254587, 0.51905027])

In [27]:
# np.linspace(S.V,E.V,n)  n---> it is number of partition 
# it is used to divide the given range from range from s.v to e.v  in to n equal parts


np.linspace(1,20,4)


array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [28]:
# np.zeros() ---->Initialize an array or matrix with all zero values (often used before filling it with other data).

arr = np.zeros((3, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
# np.ones() ------> Creates an array filled with all ones.


arr = np.ones((2, 4))
print((arr))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
# np.identity() ------> Creates a square identity matrix — a matrix with 1s on the diagonal and 0s elsewhere.

arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Copy operation

In [31]:
"""
Shallow copy:- It is sopy operation when the value space will get copied to dest_variable
Syntax:- dest_var=src_val.copy()

"""
b=np.array([1,2,3,4,5])
c=b.copy()
b[1]=10
b

array([ 1, 10,  3,  4,  5])

In [32]:
"""
View()

"""

d=np.array([1,2,3,4,5])
e=d.view()
e[2]=30
d

array([ 1,  2, 30,  4,  5])

In [33]:
# dir(np) shows all the attributes, functions, classes, and modules available inside NumPy

print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

In [34]:
"""
Difference between normal copy() & view():-
In normal copy src_var & dest_var will have same address
In view() src_var & dest_var will have different address

"""

'\nDifference between normal copy() & view():-\nIn normal copy src_var & dest_var will have same address\nIn view() src_var & dest_var will have different address\n\n'

### 11-11-25

In [35]:
# INDEXING
# var[S.V,E.V,UPDATION]
# array[row_selection, column_selection]


arr=np.array([1,2,3,4,5])
arr[2]
arr[-1]

arr[2::]                #array([3, 4, 5])
arr[::2]                #array([1, 3, 5])

array([1, 3, 5])

In [36]:
# array[row_selection, column_selection]


arr2=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2[1][2]
arr2[2][2]
arr2[1::,1::]

array([[5, 6],
       [8, 9]])

In [37]:
arr3=np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20],
               [21,22,23,24,25]])
arr3[ : :  ,3:5:1]
arr3[3:5:1 ,2:5:1]
arr3[2:5:1 ,1:4:2]   # here last index is 4 so if we take 5 then ok or we can just leave and for updation if 1 then leave space arr3[2:0:1 ,1:4:2]  
arr3[3:5:1 ,0:5:2]   # here last index is 4 so if we take 5 then ok or we can just leave and for updation if 1 then leave space arr3[3:: ,0::2] 
arr3[0:3:1 ,0:3:1]
arr3[::2,::2]
arr3[::4,::2]



array([[ 1,  3,  5],
       [21, 23, 25]])

### 13-11-25

### OPERATORS:-

##### ARITHMETIC OPERATORS

In [38]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1+arr2 #array([ 7,  9, 11, 13, 15])
np.add(arr1,arr2) #array([ 7,  9, 11, 13, 15])

array([ 7,  9, 11, 13, 15])

In [39]:
# np.add(op1,op2): it will add two arrays w.r.to index


arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1-arr2)                                      #array([-5, -5, -5, -5, -5])
print(arr2-arr1)                                      #array([5, 5, 5, 5, 5])
print(arr1*arr2)                                      #array([ 6, 14, 24, 36, 50])
print(arr1/arr2)                                      #array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])
print(arr1//arr2)                                     #array([0, 0, 0, 0, 0])
print(arr1%arr2)                                      #array([1, 2, 3, 4, 5])
print(arr1**arr2)                                     #array([      1,     128,    6561,  262144, 9765625])
print(np.power(arr1,arr2))                            #array([      1,     128,    6561,  262144, 9765625])


[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0 0 0 0 0]
[1 2 3 4 5]
[      1     128    6561  262144 9765625]
[      1     128    6561  262144 9765625]


##### RELATIONAL OPERATORS

In [40]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,3,5])
print(arr1>arr2)                                  #array([False, False, False,  True, False])
print(arr1>=arr2)                                 #array([ True,  True,  True,  True,  True])
print(arr1<arr2)                                  #array([False, False, False, False, False])
print(arr1<=arr2)                                 #array([ True,  True,  True, False,  True])
print(arr1!=arr2)                                 #array([False, False, False,  True, False])
print(arr1==arr2)                                 #array([ True,  True,  True, False,  True])

[False False False  True False]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True False  True]
[False False False  True False]
[ True  True  True False  True]


##### BITWISE OPERATORS

In [41]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print("and",arr1&arr2)                    #and [0 2 0 0 0]
print("or",arr1|arr2)                     #or [ 7  7 11 13 15]
print("not",~arr1)                        #not [-2 -3 -4 -5 -6]
print("xor",arr1^arr2)                    #xor [ 7  5 11 13 15]

and [0 2 0 0 0]
or [ 7  7 11 13 15]
not [-2 -3 -4 -5 -6]
xor [ 7  5 11 13 15]


##### LOGICAL OPERATORS

In [42]:
print(np.logical_and(arr1,arr2))           #array([ True,  True,  True,  True,  True])
print(np.logical_or(arr1,arr2))            #array([ True,  True,  True,  True,  True])
print(np.logical_not(arr1))                #array([False, False, False, False, False])

[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


In [43]:
# np.sum(op):- It will give sum of all elements in the array
print(np.sum(arr1))                          #np.int64(15) 


# np.mean(op):- It will give the average of all the elements present in a array
print(np.mean(arr1))                         #np.float64(3.0)


# np.max(op):- It will give maximum value among the array
print(np.max(arr1))                          #np.int64(5)


# np.min:- It will give minimum value among the array
print(np.min(arr1))                          #np.int64(1)


# np.count_nonzero(op):- Count of elements
print(np.count_nonzero(arr1))                #5

15
3.0
5
1
5


##### BOOLEAN FILTERING

In [44]:
arr3=np.array([10,20,30,40,50,60,110,120])
print(arr3[arr3>30])
print(arr3[arr3>20])
print(arr3[arr3<100],"\n")

print(np.logical_and(arr3[arr3>20],arr3[arr3<100]))
print(np.logical_and(arr3>20, arr3<100),"\n")

print(arr3[np.logical_and(arr3 > 20, arr3 < 100)])
print(arr3[(arr3>20)&(arr3<100)])
print(arr3[(arr3%3==0)&(arr3%5==0)])

[ 40  50  60 110 120]
[ 30  40  50  60 110 120]
[10 20 30 40 50 60] 

[ True  True  True  True  True  True]
[False False  True  True  True  True False False] 

[30 40 50 60]
[30 40 50 60]
[ 30  60 120]


### column axis=0 row axis=1

In [45]:
stu=np.random.randint(35,100,25).reshape(5,5)
print(stu,'\n')

print(np.mean(stu))

[[97 98 95 50 73]
 [80 57 77 64 83]
 [47 55 50 62 94]
 [37 79 48 50 92]
 [96 67 73 63 62]] 

69.96


In [46]:
a=np.mean(stu,axis=0)                  #average marks per subject
print(a)

b=np.mean(stu,axis=1)                  #average marks for each student
print(b)

c=np.sum(stu,axis=0)                                          
print(c)

d=np.max(stu,axis=0)                                          
print(d)

e=stu[stu>70]
print(e)

[71.4 71.2 68.6 57.8 80.8]
[82.6 72.2 61.6 61.2 72.2]
[357 356 343 289 404]
[97 98 95 64 94]
[97 98 95 73 80 77 83 94 79 92 96 73]


In [47]:
f=np.count_nonzero(e)
print(f)

g=np.min(stu,axis=0)
print(g)

h=np.min(stu,axis=1)
print(h)

i=(np.sum(stu,axis=1)/500)*100
print(i)

j=i[i>70]
print(j)

12
[37 55 48 50 62]
[50 57 47 37 62]
[82.6 72.2 61.6 61.2 72.2]
[82.6 72.2 72.2]


In [48]:
k=np.count_nonzero(j)
print(k)


l=np.mean(stu,axis=1)
print(l)

m=np.count_nonzero(l>70)
print(m)

3
[82.6 72.2 61.6 61.2 72.2]
3


In [49]:
# np.sort:- It will arrange in ascending order

arr=np.array([10,50,30,40,60])
np.sort(arr)

array([10, 30, 40, 50, 60])

In [50]:
arr1=np.array([10,20,30,40,50,60])
arr2=arr1.reshape(2,3)
print(arr2,'\n')

print(arr2.reshape(-1))

[[10 20 30]
 [40 50 60]] 

[10 20 30 40 50 60]


In [51]:
# ravel:- It is similar to reshape. The only difference is that ravel is faster than reshape

print(arr2.reshape(-1))
print(arr2.ravel())

[10 20 30 40 50 60]
[10 20 30 40 50 60]


#### advance indexing (fancy indexing)

In [52]:
# var[[row],[column]]--->fancy indexing row---->var[[]] or var[row] column---->var[:,[col]] for multiple rows: var[[row1,row2]]

arr7=np.array([[10,20,30],
       [40,50,60],
       [70,80,90]])

print(arr7[[0,1,2,2],[1,2,0,2]],'\n')
print(arr7[1],'\n')
print(arr7[:,[2]],'\n')

[20 60 70 90] 

[40 50 60] 

[[30]
 [60]
 [90]] 



In [53]:
arr1=np.array([[1,2,3,4,5],
               [10,20,30,40,50],
               [60,70,80,90,100],
               [110,120,130,140,150],
               [160,170,180,190,200]])
print(arr1[[4],[3,4]])
print(arr1[4])
print(arr1[[0,1,2]])
print(arr1[:,[2]])
print(arr1[[0,1,4],[4,2,4]])
print(arr1[:,[2,3]])

# print(arr1[[2,4,1],[2,3]])#shape mismatch

[190 200]
[160 170 180 190 200]
[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [ 60  70  80  90 100]]
[[  3]
 [ 30]
 [ 80]
 [130]
 [180]]
[  5  30 200]
[[  3   4]
 [ 30  40]
 [ 80  90]
 [130 140]
 [180 190]]


In [54]:
a=np.array([[25,10],
            [30,9],
            [32,8],
            [24,6],
            [39,9],
            [27,4],
            [29,5],
            [33,3],
            [38,11],
            [40,7]])
temp=a[:,[0]]
print(np.mean(temp))
min=np.min(temp)
max=np.max(temp)
print(max,min)
print(np.subtract(max,min))

31.7
40 24
16


In [55]:
"""
Broadcasting:- It is a phenomena of doing operations between different shapes of arrays
               Broadcasting is not possible when elements inside a row or column mismatch, or due to shape mismatch
"""

arr=np.array([10,20,30,40])
arr1=np.array(10)
arr+arr1

array([20, 30, 40, 50])

In [56]:
arr3=np.array([[1,2,3],[4,5,6]])
arr4=np.array([1,2,3])
arr3+arr4

array([[2, 4, 6],
       [5, 7, 9]])

In [57]:
arr5=np.array([[3,5,7],
               [6,8,10]])
arr6=np.array([[1],
               [2],
               [3]])
arr7=np.array(10)
arr5+arr7

array([[13, 15, 17],
       [16, 18, 20]])

In [58]:
arr8=np.arange(1,10,1).reshape(3,3)
arr8
arr9=np.arange(1,10,1).reshape(3,3)
arr9
np.add(arr8,arr9)
arr8+arr9

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [59]:
"""
np.where(condn,new_value,array): It will search the element w.r.to condition and returns the index. 
                                 It will also replace the old value with new value according to condition

"""

arr2=np.array([10,20,30,40,50])
np.where(arr2>30,100,arr2)

array([ 10,  20,  30, 100, 100])